format:
  placeholder-format: '<%ph>'

# Toggles whether you receive debug messages
debug: false

# The notification to all players when a player joins
# comment out/remove to remove it
# Listable; can be String or List
join-message:
  enabled: false
  message: '&e<player> joined the game'

# The notification to all players when a player leaves the game
# comment out/remove to remove it
# Listable; can be String or List
quit-message:
  enabled: false
  message: '&e<player> left the game'